myapp/chores/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import DataRequired

class ChoreForm(FlaskForm):
    chore = StringField('Chore', validators=[DataRequired()])
    description = StringField('Description')
    completed_by = StringField('Completed By')
    done = BooleanField('Done')
    submit = SubmitField('Post')
    

myapp/chores/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Chore
from myapp.chores.forms import ChoreForm

chores = Blueprint('chores', __name__)

@chores.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = ChoreForm()
    if form.validate_on_submit():
        chore = Chore(chore=form.chore.data, description=form.description.data, completed_by=form.completed_by.data, done=form.done.data, user_id=current_user.id)
        db.session.add(chore)
        db.session.commit()
        flash('Chore Created')
        print('Chore was created')
        return redirect(url_for('users.user_posts'))
    return render_template('create_chore.html', title='Add A Chore', form=form)

@chores.route('/<int:chore_id>')
def chore(chore_id):
    chore = Chore.query.get_or_404(chore_id) 
    return render_template('chore.html', title=chore.chore, date=chore.date, post=chore)

@chores.route('/<int:chore_id>/update',methods=['GET','POST'])
@login_required
def update(chore_id):
    chore = Chore.query.get_or_404(chore_id)

    if chore.author != current_user:
        abort(403)

    form = ChoreForm()

    if form.validate_on_submit():
        chore.chore = form.chore.data
        chore.description = form.description.data
        chore.completed_by = form.completed_by.data
        chore.done = form.done.data
        db.session.commit()
        flash('Chore Updated')
        return redirect(url_for('users.user_posts', chore_id=chore.id))

    elif request.method == 'GET':
        form.chore.data = chore.chore
        form.description.data = chore.description
        form.completed_by.data = chore.completed_by
        form.done.data = chore.done

    return render_template('create_chore.html',title='Update Chore',form=form)

@chores.route('/<int:chore_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(chore_id):

    chore = Chore.query.get_or_404(chore_id)
    if chore.author != current_user:
        abort(403)

    db.session.delete(chore)
    db.session.commit()
    flash('Chore Deleted')
    return redirect(url_for('users.user_posts'))

myapp/core/views.py
# core/views.py 
from flask import render_template, request, Blueprint
from myapp.models import Chore, User


core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    chores = Chore.query.order_by(Chore.done.asc()).paginate(page=page, per_page=5)

    return render_template('index.html', chores=chores)


@core.route('/info')
def info():
    return render_template('info.html')

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, Chore
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('users.user_posts')

            return redirect(next)

    return render_template('login.html',form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

@users.route('/account')
@login_required
def user_posts():
    username=current_user.username
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    chores = Chore.query.filter_by(author=user).order_by(Chore.done.asc()).paginate(page=page, per_page=5) 
    return render_template('user_chores.html', chores=chores, user=user)

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,500;1,200;1,400;1,700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles.css">
    <title>Chores Simplified</title>
    <link 
    id="favicon" 
    rel="icon"
    href="../static/favicon-32x32.png"
    type="image/png" 
    sizes="32x32"
    >
</head>
<body>
    <ul class="nav">
        <li class="nav-link">
            <a class="navtext" href="{{url_for('core.info')}}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-link">
            <a class="navtext" href="{{url_for('chores.create_post')}}">Add A Chore</a> 
        </li>
        <li class="nav-link">
            <a class="navtext" href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        <li class="nav-link">
            <a class="navtext" href="{{url_for('users.user_posts')}}">Account</a>
        </li>
        {% else %}
        <li class="nav-link">
            <a class="navtext" href="{{url_for('core.index')}}">Home</a>
        </li>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/chore.html
{% extends "base.html" %}
{% block content %}
<div class="show-chore">
  <h1>{{ post.chore }}</h1>
  <p>Added on: {{ post.date.strftime('%B %d, %Y') }}</p>
  <p>Description: {{post.description}}</p>
  <p>Needs To Be Completed By: {{post.completed_by}}</p>
  {% if post.done==True %}
  <p>Done: Yes</p>
  {% else %}
  <p>Done: No</p>
  {% endif %}
   {% if post.author == current_user %}
     <div class="buttons">
       <button class="chore">
       <a href="{{ url_for('chores.update', chore_id=post.id) }}">Update</a>
      </button>
       <form action="{{ url_for('chores.delete_post', chore_id=post.id) }}" method="POST">
        <input class="delete" type="submit" value="Delete">
      </form>
     </div>
   {% endif %}
</div>
{% endblock content %}

myapp/templates/create_chore.html
{% extends "base.html" %}
{% block content %}
    <div class="addchoreform">
      <form class="addchoreinput" method="POST">
        <h1>{{title}}</h1>
          {{form.hidden_tag()}}

          <div class="addchore">
              {{form.chore.label}}
              {{form.chore}}
          </div>
          <div class="addchore">
            {{form.description.label}}
            {{form.description}}
          </div>
          <div class="addchore">
            {{form.completed_by.label}}
            {{form.completed_by}}
          </div>
          <div class="addchore">
            {{form.done.label}}
            <input type="checkbox" name="done">
          </div>
          
          <div class="addchorebutton">
            {{form.submit}}
          </div>
      </form>
    </div>
    <img class="addchoreimg" src="../static/PinClipart.com_janitor-clipart_150824.png" alt="">
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="allhomepage">
    <img class="homeimage" src="../static/AibjGkXbT.gif" alt="">    
    <div class="homepage">
    {% if current_user.is_authenticated %}
    <h1>Welcome to Chores Simplified!</h1>
    <h3>The app that helps you get things done.</h3>
    {% else %}
    <h1>Welcome to Chores Simplified!</h1>
    <h3>The app that helps you get things done.</h3>
    <button class="homebutton"><a class="navtext" href="{{url_for('users.login')}}">Log In</a></button>
    <button class="homebutton"><a class="navtext" href="{{url_for('users.register')}}">Register</a></button><br>
    {% endif %}
    </div>
    </div>

{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="about">
        <h1>About Chores Simplified</h1>
        <p>This an app to help help people organize their chores and get things done!</p>
    </div>
    <img class="addchoreimg" src="../static/PinClipart.com_janitor-clipart_150824.png" alt="">
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="loginpage">
    <h1>Log In:</h1>
    <form class="loginform" method="POST">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        <div class="loginbutton">
            {{form.submit()}}
        </div>
    </form>
</div>
<img class="brooms" src="../static/brooms-vector-cartoon_7kLf6b_SB_PM.jpg" alt="dancing broom">
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
<form class="registerform" method="POST">
    <img class="registerimg" src="../static/istockphoto-1224047078-170667a.jpg" alt="spray bottle">
    <div>
    <h1>Register:</h1>
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    <div class="registerbutton">
    {{form.submit()}}
    </div>
    </div>
</form>

{% endblock %}

myapp/templates/user_chores.html
{% extends "base.html" %}
{% block content %}
    <div>
                <h1>My Chores</h1><br>
    <div class="allchorespage">
    {% if current_user.posts %}
     {% for post in chores.items %}
    <div class="all-chores">
    <button class="choredetails">
        <a href="{{url_for('chores.chore', chore_id=post.id)}}">Get Chore Details</a>
    </button>
    <h3 class="choretitle">{{post.chore}}</h3>
    <p>Added on: {{post.date.strftime("%y-%m-%d")}}</p>
    <p>Description: {{post.description}}</p>
    {% if post.done==True %}
    <p>Done: Yes</p>
    {% else %}
    <p>Done: No</p>
    {% endif %}
    </div>
    {% endfor %}

    {% else %}
    <h3>You have no chores. Nice!</h3>
    {% endif %}
    </div>
    </div>
    
    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">

            {% for page_num in chores.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if chores.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>


{% endblock %}